services:
  golang-app:
    build: .
    container_name: golang-app
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nxt
      REDIS_HOST: redis
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/?sslmode=disable
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/nxt?sslmode=disable
      JWT_SECRET: myJWTSecretIsSuperHard
      REDIS_URL: redis:6379
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nxt
    ports:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"  # RabbitMQ management UI
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
