CREATE TABLE "users" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" varchar(50) UNIQUE,
                         "email" varchar(100) UNIQUE,
                         "password" varchar(255),
                         "first_name" varchar(50),
                         "last_name" varchar(50),
                         "auth_key" varchar(512) UNIQUE,
                         "created_at" timestamp DEFAULT (current_timestamp),
                         "updated_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "user_configurations" (
                                       "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       "user_id" int,
                                       "latest_change_only" boolean DEFAULT true,
                                       "retry_failure" boolean DEFAULT true,
                                       "max_retries" int DEFAULT 5
);

CREATE TABLE "actions" (
                           "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "user_id" int,
                           "event_name" varchar(255),
                           "created_at" timestamp DEFAULT (current_timestamp),
                           "updated_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "subscribers" (
                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "user_id" int,
                               "webhook_link" varchar(512),
                               "secret_token" varchar(512),
                               "is_verified_domain" boolean DEFAULT true,
                               "is_active" boolean DEFAULT true,
                               "created_at" timestamp DEFAULT (current_timestamp),
                               "updated_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "subscriber_actions" (
                                      "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "subscriber_id" int,
                                      "action_id" int,
                                      "created_at" timestamp DEFAULT (current_timestamp),
                                      "updated_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "changes" (
                           "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "user_id" int,
                           "action_id" int,
                           "data" json,
                           "identifier" varchar(128),
                           "when" timestamp,
                           "created_at" timestamp DEFAULT (current_timestamp),
                           "updated_at" timestamp DEFAULT (current_timestamp)
);

CREATE TABLE "webhook_log" (
                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "user_id" int,
                               "change" int,
                               "subscriber_id" int,
                               "status" varchar(32) DEFAULT 'pending',
                               "retries" int DEFAULT 0,
                               "status_code" int,
                               "response_text" varchar(512),
                               "created_at" timestamp DEFAULT (current_timestamp),
                               "updated_at" timestamp DEFAULT (current_timestamp)
);

CREATE UNIQUE INDEX ON "subscribers" ("user_id", "webhook_link");

CREATE UNIQUE INDEX ON "subscriber_actions" ("subscriber_id", "action_id");

COMMENT ON COLUMN "changes"."when" IS 'time happening on user side';

ALTER TABLE "user_configurations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "actions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "subscribers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "subscriber_actions" ADD FOREIGN KEY ("subscriber_id") REFERENCES "subscribers" ("id");

ALTER TABLE "subscriber_actions" ADD FOREIGN KEY ("action_id") REFERENCES "actions" ("id");

ALTER TABLE "changes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "changes" ADD FOREIGN KEY ("action_id") REFERENCES "actions" ("id");

ALTER TABLE "webhook_log" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "webhook_log" ADD FOREIGN KEY ("change") REFERENCES "changes" ("id");

ALTER TABLE "webhook_log" ADD FOREIGN KEY ("subscriber_id") REFERENCES "subscribers" ("id");